accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),

    path("logout/", auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name="logout"),
    path("signup/", views.SignUp.as_view(), name="signup"),
    path("profile/", views.ProfileUpdate.as_view(), name="profile"),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='accounts/password_change.html',success_url='done'),  name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html'), name='done'),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

csvs/urls.py
from django.urls import path
from .views import upload_file_view

app_name = 'csvs'

urlpatterns = [
    path('', upload_file_view,name='upload-view'),
]

myapp/urls.py
from django.contrib import admin 
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = 'myapp'

urlpatterns = [
    path('', views.index,name='index'),
    path('about/',views.AboutView.as_view(),name='about'),
    path('thanks/', views.ThanksPage.as_view(), name="thanks"),
    path('importer/', views.simple_upload,name='importer'),
]

myapp/models.py
# myapp
from django.db import models
from django.contrib.auth.models import User 


class Agency(models.Model):
    system_name = models.CharField(max_length=255)
    county = models.CharField(max_length=60)
    state = models.CharField(max_length=2)
    active = models.BooleanField(default=True)


    system_type_tuple = [('C', 'Community'),('NC','Non-Community'),('NP','Irrigation'),('TC','Temporary Community'),('UN','Unknown')]
    system_type = models.CharField(max_length=2, choices=system_type_tuple, default= 'UN')
    address = models.CharField(max_length=255, blank=True)
    city = models.CharField(max_length=60, blank=True)
    zipcode = models.CharField(max_length=5, blank=True)
    system_no = models.CharField(max_length=7, unique=True)
    class Meta:
        unique_together = ('system_name', 'system_no',)
    
    def __str__(self):
        return self.system_name

# class SystemNumber(models.Model):
#     system_name = models.ForeignKey(Agency, on_delete=models.CASCADE)

    
    
#     def __str__(self):
#         return self.system_no

class County(models.Model):
    coid = models.PositiveSmallIntegerField(default=0)
    name = models.CharField(max_length=60)
    def __str__(self):
        return self.name

class SitePart(models.Model):
    system_no = models.ForeignKey('Agency', on_delete=models.CASCADE)
    # part name is only unique for the system number other systems will have the same of simular name
    part_name = models.CharField(max_length=125, unique=True) 
    status_tuple = [('AB','Abandoned'),('DS','Destroyed'),('IA','Inactive'),('AR','Active Recorder'),('AT','Active Treatment Facility'),('SB','Stand By waiting acitvation'),('MO','Monitoring')]
    status = models.CharField(max_length=2, choices=status_tuple, default= 'SB')
    # sys_site_n system site number is ID that uses the system number plus additional numbers that is specific for the part_name
    sys_site_n = models.CharField(max_length=15, unique=True)

    def __str__(self):
        return self.loc_name

myapp/views.py
from django.shortcuts import render
from .resources import AgencyResource
from tablib import Dataset

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required # this one requires login from user. 
from django.views.generic import (TemplateView, ListView, DetailView)


class AboutView(TemplateView):
    template_name = 'myapp/about.html'
class ThanksPage(TemplateView):
    template_name = 'myapp/thanks.html'
class RegisterPage(TemplateView):
    template_name = 'myapp/register.html'

# Create your views here.
def index(request):
    return render(request, 'myapp/index.html')


# def export(request):
#     agency_resource = AgencyResource()
#     dataset = agency_resource.export()
#     response = HttpResponse(dataset.csv, content_type='text/csv')
#     response['Content-Disposition'] = 'attachment; filename="agency.csv"'
#     return response

def simple_upload(request):
    if request.method == 'POST':
        agency_resource = AgencyResource()
        dataset = Dataset()
        new_r = request.FILES['myfile']
        imported_data = Dataset().load(new_r.read().decode("utf-8"), format='csv')
        result = agency_resource.import_data(dataset, dry_run=True)  # Test the data import, give raise_errors = True as last parameter if you want to see errors.
        if not result.has_errors():
            agency_resource.import_data(dataset, dry_run=False)  # Actually import now
    return render(request, 'myapp/importer.html')

templates/myapp/about.html
{% extends "myapp/base.html" %}
{% block body_block %}
<div>
<h1>About Me</h1>
<p>This site is currently being built.</p>
</div>
{% endblock %}

templates/myapp/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

      <!-- <link rel="stylesheet" type='text/css' href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css">
      <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script> -->

    </head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'home' %}">Community Data</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'myapp:about' %}">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" href="{% url 'accounts:signup' %}">Registration</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" href="{% url 'csvs:upload-view' %}">Upload File</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'myapp:importer' %}">Import CSV</a>
              </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link active" href="{% url 'accounts:profile' %}">Profile Changes</a>
                </li>
                <li class="nav-item"><a class='nav-link active' href="{% url 'logout' %}">Logout</a></li>

                <li class="nav-item">
                  <a class="nav-link active" >Welcome: {{ user.username }}</a>
                </li>

                {% else %}
                <li class="nav-item">
                  <a class='nav-link active' href="{% url 'login' %}">Login</a>
                </li>
                {% endif %}

            </ul>
          </div>
        </div>
      </nav>
      <div class="container px-5">
          {% block body_block %}
          <!-- Anythin outside of this will be inherited if you extend! -->
          {% endblock %}
      </div>
</body>
</html>

templates/myapp/importer.html
{% extends "myapp/base.html" %}
{% block body_block %}
  {% if success_import %}
  <div class="alert alert-success" role="alert">
      {{ success_import}}
  </div>
  {% elif error_import %}
  <div class="alert alert-warning" role="alert">
      {{ error_import}}
  </div>
  {% endif %}
  <h1>Please select csv or xlsx file to Import</h1>
  <form method="post" enctype="multipart/form-data" class="form-control">
    {% csrf_token %}
    <input type="file" class="" name="myfile">
    <button type="submit" class="btn btn-primary">Upload</button>
  </form>
  <div>
  <li>
    Let's check the import: <a href="{% url 'admin:index' %}">Admin</a>
  </li>
  </div>
<h3> This one is not working right. </h3>
<p>I would like to develop this to import all types of tables that match the data fields in the myapp/models.py </p>
<p>I would like to import both csv and xlsx files. I think I can figure this one out but haven't had the time to do so yet.</p>
{% endblock %}

templates/myapp/index.html
{% extends "myapp/base.html" %}
{% block body_block %}


<div class="rounded-pill p-5 bg-info position-absolute top-50 start-50 translate-middle">
    <br><br>
    <h1 class="text-center">  Agency Helper  </h1>
    <h3 class="text-center">Get Community Data Stats</h3>
    <br><br>

</div>
{% endblock %}

templates/myapp/test.html
{% extends "myapp/base.html" %}
{% block body_block %}
<div class="container">
  <h1>You are now logged in!</h1>


</div>

{% endblock %}

templates/myapp/thanks.html
{% extends "myapp/base.html" %}
{% block body_block %}
<div class="rounded-pill p-5 bg-info position-absolute top-50 start-50 translate-middle">

  <h1>Thank you for signing up</h1>


</div>

{% endblock %}